### ISSUE TITLE
QUEST - its possible GET from the API (before) the rewards from event pass?

### ISSUE THREAD

**Issue by Neinndall** [BlossomiShymae/llux#4]
I was looking for a way to datamine the ITEMS of the events such as the worlds 2023, in the api it is called /v1/rewards-track-items which should output the different levels with the corresponding items (tokens, emotes...) I don't know Whether this can be datamined ahead of time or can only be obtained when RIOT adds it.

**Comment by BlossomiShymae** [comment]
I am unfamilar with that endpoint, but probs when Riot adds it in. Like all other LCU endpoint usage, it is largely undocumented by the community. I'm unable to help with such issues. :>

Feel free to open up another issue if it pertains to llux. 💜
